//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maroontress.Oxbind.Impl {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oxbind.Maroontress.Oxbind.Impl.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ElementSchema] must not be combined with [ForText]: {0} and {1}.
        /// </summary>
        internal static string both_ForText_and_ElementSchema {
            get {
                return ResourceManager.GetString("both_ForText_and_ElementSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ForText] must not be combined with [FromText]: {0} and {1}.
        /// </summary>
        internal static string both_ForText_and_FromText {
            get {
                return ResourceManager.GetString("both_ForText_and_FromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ElementSchema] must not be combined with [FromText]: {0} and {1}.
        /// </summary>
        internal static string both_FromText_and_ElementSchema {
            get {
                return ResourceManager.GetString("both_FromText_and_ElementSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicated attribute name: &apos;{0}&apos; at {1}.
        /// </summary>
        internal static string duplicated_attribute_name {
            get {
                return ResourceManager.GetString("duplicated_attribute_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicated child element class: {0} at {1}.
        /// </summary>
        internal static string duplicated_child_class {
            get {
                return ResourceManager.GetString("duplicated_child_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicated child element name: &apos;{0}&apos; at {1}.
        /// </summary>
        internal static string duplicated_element_name {
            get {
                return ResourceManager.GetString("duplicated_element_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must not have two or more [ElementSchema]s: {0}.
        /// </summary>
        internal static string duplicated_ElementSchema {
            get {
                return ResourceManager.GetString("duplicated_ElementSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must not have two or more [ForText]s: {0}.
        /// </summary>
        internal static string duplicated_ForText {
            get {
                return ResourceManager.GetString("duplicated_ForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must not have two or more [FromText]s: {0}.
        /// </summary>
        internal static string duplicated_FromText {
            get {
                return ResourceManager.GetString("duplicated_FromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ElementSchema] is ignored for instance fields: {0}.
        /// </summary>
        internal static string ElementSchema_is_ignored {
            get {
                return ResourceManager.GetString("ElementSchema_is_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ForAttribute] is ignored for static fields: {0}.
        /// </summary>
        internal static string ForAttribute_is_ignored {
            get {
                return ResourceManager.GetString("ForAttribute_is_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unused [ForChild] or [FromChild] attributes: {0} at {1}.
        /// </summary>
        internal static string ForChild_FromChild_is_unused {
            get {
                return ResourceManager.GetString("ForChild_FromChild_is_unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ForChild] is ignored for static fields: {0}.
        /// </summary>
        internal static string ForChild_is_ignored {
            get {
                return ResourceManager.GetString("ForChild_is_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ForText] is ignored for static fields: {0}.
        /// </summary>
        internal static string ForText_is_ignored {
            get {
                return ResourceManager.GetString("ForText_is_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FromAttribute] is ignored for static methods: {0}.
        /// </summary>
        internal static string FromAttribute_is_ignored {
            get {
                return ResourceManager.GetString("FromAttribute_is_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FromChild] is ignored for static fields: {0}.
        /// </summary>
        internal static string FromChild_is_ignored {
            get {
                return ResourceManager.GetString("FromChild_is_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FromText] is ignored for static methods: {0}.
        /// </summary>
        internal static string FromText_is_ignored {
            get {
                return ResourceManager.GetString("FromText_is_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be annotated with [ForElement].
        /// </summary>
        internal static string must_be_annotated_with_ForElement {
            get {
                return ResourceManager.GetString("must_be_annotated_with_ForElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must not be interface.
        /// </summary>
        internal static string must_not_be_interface {
            get {
                return ResourceManager.GetString("must_not_be_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the type that the Schema object contains is not the class annotated with [ForElement]: {0}.
        /// </summary>
        internal static string not_annotated_with_ForElement {
            get {
                return ResourceManager.GetString("not_annotated_with_ForElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the type in the Schema object is not handled with [ForChild] or [FromChild]: {0}.
        /// </summary>
        internal static string not_handled_class {
            get {
                return ResourceManager.GetString("not_handled_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the type of the field annotated with [ElementSchema] is not Schema class: {0}.
        /// </summary>
        internal static string type_mismatch_ElementSchema {
            get {
                return ResourceManager.GetString("type_mismatch_ElementSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the type of the field annotated with [ForAttribute] is not string: {0}.
        /// </summary>
        internal static string type_mismatch_ForAttribute {
            get {
                return ResourceManager.GetString("type_mismatch_ForAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the type of the field annotated with [ForText] is not string: {0}.
        /// </summary>
        internal static string type_mismatch_ForText {
            get {
                return ResourceManager.GetString("type_mismatch_ForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the signature of the method annotated with [FromAttribute] is not void(string): {0}.
        /// </summary>
        internal static string type_mismatch_FromAttribute {
            get {
                return ResourceManager.GetString("type_mismatch_FromAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the method annotated with [FromChild] must have a single parameter and return void: {0}.
        /// </summary>
        internal static string type_mismatch_FromChild {
            get {
                return ResourceManager.GetString("type_mismatch_FromChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the type of the method annotated with [FromText] is not void(string): {0}.
        /// </summary>
        internal static string type_mismatch_FromText {
            get {
                return ResourceManager.GetString("type_mismatch_FromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
